// TODO: Replace with "say -v '?'"
export default [
  { name: 'Agnes', locale: 'en_US' },
  { name: 'Albert', locale: 'en_US' },
  { name: 'Alex', locale: 'en_US' },
  { name: 'Alice', locale: 'it_IT' },
  { name: 'Alva', locale: 'sv_SE' },
  { name: 'Amelie', locale: 'fr_CA' },
  { name: 'Anna', locale: 'de_DE' },
  { name: 'Bad News', locale: 'en_US' },
  { name: 'Bahh', locale: 'en_US' },
  { name: 'Bells', locale: 'en_US' },
  { name: 'Boing', locale: 'en_US' },
  { name: 'Bruce', locale: 'en_US' },
  { name: 'Bubbles', locale: 'en_US' },
  { name: 'Carmit', locale: 'he_IL' },
  { name: 'Cellos', locale: 'en_US' },
  { name: 'Damayanti', locale: 'id_ID' },
  { name: 'Daniel', locale: 'en_GB' },
  { name: 'Deranged', locale: 'en_US' },
  { name: 'Diego', locale: 'es_AR' },
  { name: 'Ellen', locale: 'nl_BE' },
  { name: 'Fiona', locale: 'en-scotland' },
  { name: 'Fred', locale: 'en_US' },
  { name: 'Good News', locale: 'en_US' },
  { name: 'Hysterical', locale: 'en_US' },
  { name: 'Ioana', locale: 'ro_RO' },
  { name: 'Joana', locale: 'pt_PT' },
  { name: 'Junior', locale: 'en_US' },
  { name: 'Kanya', locale: 'th_TH' },
  { name: 'Karen', locale: 'en_AU' },
  { name: 'Kathy', locale: 'en_US' },
  { name: 'Kyoko', locale: 'ja_JP' },
  { name: 'Laura', locale: 'sk_SK' },
  { name: 'Lekha', locale: 'hi_IN' },
  { name: 'Luciana', locale: 'pt_BR' },
  { name: 'Mariska', locale: 'hu_HU' },
  { name: 'Mei-Jia', locale: 'zh_TW' },
  { name: 'Melina', locale: 'el_GR' },
  { name: 'Milena', locale: 'ru_RU' },
  { name: 'Moira', locale: 'en_IE' },
  { name: 'Monica', locale: 'es_ES' },
  { name: 'Nora', locale: 'nb_NO' },
  { name: 'Paulina', locale: 'es_MX' },
  { name: 'Pipe Organ', locale: 'en_US' },
  { name: 'Princess', locale: 'en_US' },
  { name: 'Ralph', locale: 'en_US' },
  { name: 'Samantha', locale: 'en_US' },
  { name: 'Sara', locale: 'da_DK' },
  { name: 'Satu', locale: 'fi_FI' },
  { name: 'Sin-ji', locale: 'zh_HK' },
  { name: 'Tarik', locale: 'ar_SA' },
  { name: 'Tessa', locale: 'en_ZA' },
  { name: 'Thomas', locale: 'fr_FR' },
  { name: 'Ting-Ting', locale: 'zh_CN' },
  { name: 'Trinoids', locale: 'en_US' },
  { name: 'Veena', locale: 'en_IN' },
  { name: 'Vicki', locale: 'en_US' },
  { name: 'Victoria', locale: 'en_US' },
  { name: 'Whisper', locale: 'en_US' },
  { name: 'Xander', locale: 'nl_NL' },
  { name: 'Yelda', locale: 'tr_TR' },
  { name: 'Yuna', locale: 'ko_KR' },
  { name: 'Zarvox', locale: 'en_US' },
  { name: 'Zosia', locale: 'pl_PL' },
  { name: 'Zuzana', locale: 'cs_CZ' }
];
